PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
Server={{.zabbix_server_ip}}
ListenIP=127.0.0.1
ServerActive={{.zabbix_server_ip}}:{{.zabbix_server_port}}
Hostname=127.0.0.1
HostMetadata=Linux         # 用于自动发现
Timeout=20
AllowRoot=1
Include=/etc/zabbix/zabbix_agentd.d/*.conf
LoadModulePath=/usr/lib/zabbix/agent
LoadModule=zabbix_module_docker.so